### ISSUE TITLE
TNT set off by redstone

### ISSUE THREAD

**Issue by ericksoncohen** [fabricservertools/DeltaLogger#70] opened 2021-04-16 15:23 UTC
When TNT is set off by any Redstone input: lever, button, pressure plate, dispenser, Redstone block, Redstone wire, observer, etc. It does not log the blocks blown up, I think that this should log all blocks blown up by any TNT even if there is no "player" that set it off.

**Comment by yitzy299** [comment] 2021-04-16 15:26
Duplicate of #59

**Closed by yitzy299** 2021-04-16 15:26 UTC
Labels: bug
